# Generated by Django 5.2 on 2025-07-05 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_department_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='advisor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'Teachers'), ('is_teacher', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='班主任'),
        ),
    ]
