# Generated by Django 5.2 on 2025-07-01 10:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(choices=[(1, '第1周'), (2, '第2周'), (3, '第3周'), (4, '第4周'), (5, '第5周'), (6, '第6周'), (7, '第7周'), (8, '第8周'), (9, '第9周'), (10, '第10周'), (11, '第11周'), (12, '第12周'), (13, '第13周'), (14, '第14周'), (15, '第15周'), (16, '第16周'), (17, '第17周'), (18, '第18周'), (19, '第19周'), (20, '第20周'), (21, '第21周'), (22, '第22周'), (23, '第23周'), (24, '第24周'), (25, '第25周'), (26, '第26周'), (27, '第27周'), (28, '第28周'), (29, '第29周'), (30, '第30周'), (31, '第31周'), (32, '第32周'), (33, '第33周'), (34, '第34周'), (35, '第35周'), (36, '第36周'), (37, '第37周'), (38, '第38周'), (39, '第39周'), (40, '第40周'), (41, '第41周'), (42, '第42周'), (43, '第43周'), (44, '第44周'), (45, '第45周'), (46, '第46周'), (47, '第47周'), (48, '第48周'), (49, '第49周'), (50, '第50周'), (51, '第51周'), (52, '第52周')], verbose_name='周次')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='实习单位')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='岗位')),
                ('status', models.CharField(choices=[('job', '求职中'), ('intern', '实习中'), ('signed', '已签约'), ('other', '其他')], default='intern', max_length=20, verbose_name='就业状态')),
                ('content', models.TextField(verbose_name='实习内容与进展')),
                ('problems', models.TextField(blank=True, verbose_name='遇到的问题')),
                ('feedback', models.TextField(blank=True, verbose_name='教师反馈')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='需紧急关注')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('can_view_report', '可以查看所有报告'), ('can_change_report', '可以修改任何报告')],
            },
        ),
    ]
