# Generated by Django 5.2 on 2025-07-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('can_view_report', '可以查看所有报告'), ('can_change_report', '可以修改任何报告'), ('can_view_own_report', '可以查看自己的报告')]},
        ),
    ]
