# Generated by Django 5.2 on 2025-07-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
