# Generated by Django 5.2 on 2025-07-06 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_comments_report_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='reports.report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '报告评论',
                'verbose_name_plural': '报告评论',
                'ordering': ['-created_at'],
            },
        ),
    ]
