# Generated by Django 5.2 on 2025-07-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': [('can_view_all_reports', '可以查看所有报告'), ('can_change_any_report', '可以修改任何报告'), ('can_view_own_report', '可以查看自己的报告'), ('can_create_report', '可以创建报告')]},
        ),
    ]
