# Generated by Django 5.2 on 2025-07-03 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code'], 'permissions': [('view_teacher_dashboard', '可以查看教师仪表板')], 'verbose_name': '院系', 'verbose_name_plural': '院系'},
        ),
    ]
